# Generated by Django 4.1 on 2022-12-14 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("quiz", "0003_quizquestion_rename_quizanswer_quizstudentanswer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="creator",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
