# Generated by Django 4.1 on 2022-12-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_quiz_creator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="discription",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
