# Generated by Django 4.1 on 2022-12-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_quizstudentanswer_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizquestion",
            name="mark",
            field=models.FloatField(default=1.0),
        ),
    ]
