# Generated by Django 4.1 on 2022-12-15 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_quizquestion_mark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizstudentanswer",
            name="answerJson",
        ),
        migrations.CreateModel(
            name="QuizStudentAnswerOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "std_answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.quizanswersoption",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizStudentAnserItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answers", models.ManyToManyField(to="quiz.quizstudentansweroption")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quiz.quizquestion",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quizstudentanswer",
            name="answers",
            field=models.ManyToManyField(to="quiz.quizstudentanseritem"),
        ),
    ]
