# Generated by Django 4.1 on 2022-12-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_remove_quizstudentanswer_answerjson_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizstudentanseritem",
            old_name="answers",
            new_name="options",
        ),
    ]
