# Generated by Django 4.1 on 2022-12-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0010_rename_answers_quizstudentanseritem_options"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QuizStudentAnserItem",
            new_name="QuizStudentAnswerItem",
        ),
    ]
