# Generated by Django 4.1 on 2022-12-15 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0011_rename_quizstudentanseritem_quizstudentansweritem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizstudentansweritem",
            name="options",
        ),
        migrations.RemoveField(
            model_name="quizstudentansweritem",
            name="question",
        ),
        migrations.RemoveField(
            model_name="quizstudentansweroption",
            name="std_answer",
        ),
        migrations.DeleteModel(
            name="QuizStudentAnswer",
        ),
        migrations.DeleteModel(
            name="QuizStudentAnswerItem",
        ),
        migrations.DeleteModel(
            name="QuizStudentAnswerOption",
        ),
    ]
