# Generated by Django 4.1 on 2022-12-15 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_stat", "0002_alter_userstat_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userstat",
            old_name="no_of_questions",
            new_name="total_score",
        ),
    ]
