# Generated by Django 4.1 on 2022-12-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_stat", "0003_rename_no_of_questions_userstat_total_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userstat",
            name="correct",
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name="userstat",
            name="incorrect",
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name="userstat",
            name="over_all_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="userstat",
            name="total_score",
            field=models.IntegerField(default=0.0),
        ),
    ]
